# Generated by Django 4.2.2 on 2023-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_details', models.TextField(max_length=100)),
                ('task_create_at', models.DateField(auto_now_add=True)),
                ('task_dateline', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
