# Generated by Django 4.2.2 on 2023-06-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ['-task_title']},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-task_name']},
        ),
        migrations.AlterModelTable(
            name='detail',
            table='task_details',
        ),
        migrations.AlterModelTable(
            name='info',
            table='Info',
        ),
    ]
