# Generated by Django 4.2.2 on 2023-06-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_tasks', '0002_alter_detail_options_alter_info_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_tasks.detail'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='task_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
