# Generated by Django 4.2.2 on 2023-06-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_tasks', '0003_info_info_title_alter_detail_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='task_dateline',
            new_name='task_deadline',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_title',
            new_name='task_priority',
        ),
    ]
