# Generated by Django 4.2.2 on 2023-06-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_tasks', '0004_rename_task_dateline_info_task_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='task_details',
        ),
    ]
