# Generated by Django 4.2.2 on 2023-06-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_tasks', '0007_rename_task_priority_info_info_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='task_deadline',
            field=models.TimeField(verbose_name=ValueError),
        ),
    ]
