# Generated by Django 4.2.2 on 2023-06-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_tasks', '0011_alter_info_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_tasks.detail'),
        ),
    ]
