# Generated by Django 4.2.2 on 2023-07-04 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_tasks', '0012_alter_info_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='task_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
