# Generated by Django 4.2.2 on 2023-07-08 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_tasks', '0013_alter_info_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='task_deadline',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
